name = "blazenote-backend"
main = "src/index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
database_name = "blazenote"
database_id = "4aea0868-6bfb-4d1c-a5a1-5cf226b9af3d"
migrations_dir = "./migrations"

# [ai]
# binding = "AI"

[[r2_buckets]]
bucket_name = "blazenote"
binding = "R2_BUCKET"
# preview_bucket_name = "dev-blazenote"

# [vars]
# VITE_API_BASE_URL = "https://blazenote-backend.kind-jukebox.workers.dev"  # Replace with your backend domain

[observability.logs]
enabled = true